# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dae194405e04c06de28418bc8021ec64"
name = "profitable"
application_url = "https://salvador-tracked-arnold-collection.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-f83a59a1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://salvador-tracked-arnold-collection.trycloudflare.com/auth/callback",
  "https://salvador-tracked-arnold-collection.trycloudflare.com/auth/shopify/callback",
  "https://salvador-tracked-arnold-collection.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
